import { AggregateRoot } from '@core/domain';
import { DomainException } from '@core/common';
import { CategoryCreatedEvent } from '../events/category-created.event';
import { CategoryUpdatedEvent } from '../events/category-updated.event';
import { CategoryDeletedEvent } from '../events/category-deleted.event';
import type { IEventMetadata } from '@core/domain';
import { CategoryId } from '../value-objects/category-id.value-object';

/**
 * Category Properties
 *
 * Story 4.1: Manage Categories
 */
export interface CategoryProps {
  value: string; // Unique key (e.g., "EMERGENCY", "SERVICES")
  label: string; // Display name (e.g., "Emergency Alerts")
  description?: string;
  color?: string; // Hex color code (e.g., "#FF0000")
  icon?: string; // Icon name or emoji (e.g., "🚨")
  isActive: boolean;
  sortOrder: number; // Display order (lower = higher priority)
  parentId: string | null; // For hierarchical structure
  tenantId: string;
}

/**
 * Category Database Properties
 *
 * Includes id, version, timestamps, soft delete, and audit fields for reconstitution
 */
export interface CategoryDbProps extends CategoryProps {
  id: string;
  version: number;
  createdAt: Date;
  updatedAt: Date;
  isDeleted: boolean;
  deletedAt: Date | null;
  deletedBy: string | null;
  createdBy: string;
  updatedBy: string | null;
}

/**
 * Category Entity (Aggregate Root)
 *
 * Story 4.1: Manage Categories
 *
 * Represents a content category with hierarchical structure.
 * Categories organize content and support parent-child relationships.
 *
 * Business Rules:
 * - value must be unique per tenant
 * - Cannot set parent to self or descendant (prevents circular references)
 * - Cannot delete category with active children
 * - sortOrder determines display priority (1 = highest)
 *
 * Domain Events:
 * - CategoryCreatedEvent
 * - CategoryUpdatedEvent
 * - CategoryDeletedEvent
 */
export class Category extends AggregateRoot {
  private _categoryId: CategoryId;
  private _props: CategoryProps;
  private _isDeleted: boolean = false;
  private _deletedAt: Date | null = null;
  private _deletedBy: string | null = null;
  private _createdBy: string;
  private _updatedBy: string | null = null;

  private constructor(
    id: CategoryId,
    version: number,
    props: CategoryProps,
    createdBy: string,
    createdAt?: Date,
    updatedAt?: Date,
    isDeleted?: boolean,
    deletedAt?: Date | null,
    deletedBy?: string | null,
    updatedBy?: string | null,
  ) {
    super(id.value, version, createdAt, updatedAt);
    this._categoryId = id;
    this._props = props;
    this._createdBy = createdBy;
    this._isDeleted = isDeleted || false;
    this._deletedAt = deletedAt || null;
    this._deletedBy = deletedBy || null;
    this._updatedBy = updatedBy || null;
  }

  // Getters
  get value(): string {
    return this._props.value;
  }

  get label(): string {
    return this._props.label;
  }

  get description(): string | undefined {
    return this._props.description;
  }

  get color(): string | undefined {
    return this._props.color;
  }

  get icon(): string | undefined {
    return this._props.icon;
  }

  get isActive(): boolean {
    return this._props.isActive;
  }

  get sortOrder(): number {
    return this._props.sortOrder;
  }

  get parentId(): string | null {
    return this._props.parentId;
  }

  get tenantId(): string {
    return this._props.tenantId;
  }

  get isDeleted(): boolean {
    return this._isDeleted;
  }

  get deletedAt(): Date | null {
    return this._deletedAt;
  }

  get deletedBy(): string | null {
    return this._deletedBy;
  }

  get createdBy(): string {
    return this._createdBy;
  }

  get updatedBy(): string | null {
    return this._updatedBy;
  }

  /**
   * Get CategoryId Value Object
   */
  get categoryId(): CategoryId {
    return this._categoryId;
  }

  // --- Helper Methods ---

  /**
   * Ensure entity is not deleted before modifications
   * Guards against modifying deleted entities
   */
  private ensureNotDeleted(): void {
    if (this._isDeleted) {
      throw new DomainException('Cannot modify deleted category');
    }
  }

  /**
   * Factory method to create a new category
   *
   * @param id Category ID (generated by handler)
   * @param props Category properties
   * @param createdBy User ID who created this category
   * @param metadata Optional event metadata
   * @returns New Category instance
   */
  public static create(
    id: CategoryId,
    props: CategoryProps,
    createdBy: string,
    metadata?: IEventMetadata,
  ): Category {
    // Validation
    if (!props.value || props.value.trim().length === 0) {
      throw new DomainException('Category value is required');
    }

    if (!props.label || props.label.trim().length === 0) {
      throw new DomainException('Category label is required');
    }

    if (props.value.length > 50) {
      throw new DomainException('Category value must be 50 characters or less');
    }

    if (props.label.length > 100) {
      throw new DomainException(
        'Category label must be 100 characters or less',
      );
    }

    if (props.sortOrder < 0) {
      throw new DomainException('Sort order must be non-negative');
    }

    const now = new Date();
    const category = new Category(
      id,
      0,
      { ...props },
      createdBy,
      now,
      now,
    );

    // Emit domain event
    category.addDomainEvent(
      new CategoryCreatedEvent(
        category.id,
        {
          tenantId: props.tenantId,
          value: props.value,
          label: props.label,
          description: props.description ?? null,
          color: props.color ?? null,
          icon: props.icon ?? null,
          isActive: props.isActive,
          sortOrder: props.sortOrder,
          parentId: props.parentId,
          createdBy,
        },
        metadata,
      ),
    );

    return category;
  }

  /**
   * Factory method to reconstitute a category from database
   *
   * @param props Category properties including id and timestamps
   * @returns Category instance
   */
  public static reconstitute(props: CategoryDbProps): Category {
    return new Category(
      new CategoryId(props.id),
      props.version,
      {
        value: props.value,
        label: props.label,
        description: props.description,
        color: props.color,
        icon: props.icon,
        isActive: props.isActive,
        sortOrder: props.sortOrder,
        parentId: props.parentId,
        tenantId: props.tenantId,
      },
      props.createdBy,
      props.createdAt,
      props.updatedAt,
      props.isDeleted,
      props.deletedAt,
      props.deletedBy,
      props.updatedBy,
    );
  }

  /**
   * Update category fields
   *
   * Business Rules:
   * - value and tenantId cannot be changed
   * - All other fields are optional
   *
   * @param updates Partial category properties to update
   * @param updatedBy User ID who updated this category
   * @param metadata Optional event metadata
   */
  public update(
    updates: Partial<Omit<CategoryProps, 'value' | 'tenantId'>>,
    updatedBy: string,
    metadata?: IEventMetadata,
  ): void {
    this.ensureNotDeleted();

    // Validation
    if (updates.label !== undefined && updates.label.trim().length === 0) {
      throw new DomainException('Category label cannot be empty');
    }

    if (updates.label !== undefined && updates.label.length > 100) {
      throw new DomainException(
        'Category label must be 100 characters or less',
      );
    }

    if (updates.sortOrder !== undefined && updates.sortOrder < 0) {
      throw new DomainException('Sort order must be non-negative');
    }

    // Apply updates
    if (updates.label !== undefined) {
      this._props.label = updates.label;
    }
    if (updates.description !== undefined) {
      this._props.description = updates.description;
    }
    if (updates.color !== undefined) {
      this._props.color = updates.color;
    }
    if (updates.icon !== undefined) {
      this._props.icon = updates.icon;
    }
    if (updates.isActive !== undefined) {
      this._props.isActive = updates.isActive;
    }
    if (updates.sortOrder !== undefined) {
      this._props.sortOrder = updates.sortOrder;
    }
    if (updates.parentId !== undefined) {
      this._props.parentId = updates.parentId;
    }

    // Update timestamp, audit, and version
    this._updatedBy = updatedBy;
    this.markAsModified();

    // Emit domain event
    this.addDomainEvent(
      new CategoryUpdatedEvent(
        this.id,
        {
          tenantId: this.tenantId,
          label: updates.label ?? null,
          description: updates.description ?? null,
          color: updates.color ?? null,
          icon: updates.icon ?? null,
          isActive: updates.isActive ?? null,
          sortOrder: updates.sortOrder ?? null,
          parentId: updates.parentId ?? null,
          updatedBy,
        },
        metadata,
      ),
    );
  }

  /**
   * Activate the category
   *
   * @param updatedBy User ID who activated this category
   * @param metadata Optional event metadata
   */
  public activate(updatedBy: string, metadata?: IEventMetadata): void {
    this.ensureNotDeleted();

    if (this._props.isActive) {
      return; // Already active, no-op
    }

    this._props.isActive = true;
    this._updatedBy = updatedBy;
    this.markAsModified();

    this.addDomainEvent(
      new CategoryUpdatedEvent(
        this.id,
        {
          tenantId: this.tenantId,
          label: null,
          description: null,
          color: null,
          icon: null,
          isActive: true,
          sortOrder: null,
          parentId: null,
          updatedBy,
        },
        metadata,
      ),
    );
  }

  /**
   * Deactivate the category
   *
   * @param updatedBy User ID who deactivated this category
   * @param metadata Optional event metadata
   */
  public deactivate(updatedBy: string, metadata?: IEventMetadata): void {
    this.ensureNotDeleted();

    if (!this._props.isActive) {
      return; // Already inactive, no-op
    }

    this._props.isActive = false;
    this._updatedBy = updatedBy;
    this.markAsModified();

    this.addDomainEvent(
      new CategoryUpdatedEvent(
        this.id,
        {
          tenantId: this.tenantId,
          label: null,
          description: null,
          color: null,
          icon: null,
          isActive: false,
          sortOrder: null,
          parentId: null,
          updatedBy,
        },
        metadata,
      ),
    );
  }

  /**
   * Mark category as deleted
   *
   * Business Rules:
   * - Emits CategoryDeletedEvent before actual deletion
   * - Repository should check for active children before allowing delete
   *
   * @param deletedBy User ID who deleted this category
   * @param metadata Optional event metadata
   */
  public markAsDeleted(deletedBy: string, metadata?: IEventMetadata): void {
    this._isDeleted = true;
    this._deletedAt = new Date();
    this._deletedBy = deletedBy;
    this.updatedAt = new Date();

    this.addDomainEvent(
      new CategoryDeletedEvent(
        this.id,
        {
          tenantId: this.tenantId,
          value: this.value,
          deletedBy,
        },
        metadata,
      ),
    );
  }
}
