export const FileTokens = {
  FILE_REPOSITORY: 'FILE_REPOSITORY',
  FILE_READ_DAO: 'FILE_READ_DAO',
  FILE_VALIDATOR: 'FILE_VALIDATOR',
  FILE_STORAGE: 'FILE_STORAGE',
  FILE_PROCESSOR: 'FILE_PROCESSOR',
  FILE_SERVICE: 'FILE_SERVICE',
  FILE_RULES_CHECKER: 'FILE_RULES_CHECKER',
} as const;

export const FILE_REPOSITORY_TOKEN = FileTokens.FILE_REPOSITORY;
export const FILE_READ_DAO_TOKEN = FileTokens.FILE_READ_DAO;
export const FILE_SERVICE_TOKEN = FileTokens.FILE_SERVICE;
export const FILE_RULES_CHECKER_TOKEN = FileTokens.FILE_RULES_CHECKER;
